"use client";
import { useEffect, useState } from "react";

interface ReviewInsightsProps {
  productId: string;
}

// AI-generated insight block for admin review dashboard.
// Content is generated by GPT-4o-mini from customer review text.
export default function ReviewInsights({ productId }: ReviewInsightsProps) {
  const [insights, setInsights] = useState<string>("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`/api/v1/reviews/insights/${productId}`)
      .then((r) => r.json())
      .then((data) => {
        setInsights(data.insights);
        setLoading(false);
      });
  }, [productId]);

  if (loading) return <div className="animate-pulse h-32 bg-gray-100 rounded" />;

  return (
    <div className="bg-white border rounded-lg p-4">
      <h3 className="text-sm font-semibold text-gray-700 mb-2">AI Review Summary</h3>
      <p className="text-sm text-gray-600 prose prose-sm whitespace-pre-wrap">{insights}</p>
    </div>
  );
}
